"""Initial migrations

Revision ID: e1abf2b48f8f
Revises: 
Create Date: 2024-02-27 14:12:52.419735

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e1abf2b48f8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('experience', sa.String(length=32), nullable=True),
    sa.Column('riding_style', sa.String(length=32), nullable=True),
    sa.Column('purpose', sa.String(length=256), nullable=True),
    sa.Column('preferences', sa.String(length=256), nullable=True),
    sa.Column('response_gpt', sa.Text(), nullable=True),
    sa.Column('id_user_telegram', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
